# Imports

In [1]:
import pandas as pd

# Import Data

In [2]:
df = pd.read_csv("dirty_cafe_sales.csv")

In [3]:
df.head(5)

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11

In [4]:
df.sample(5)

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
2807,TXN_1719440,Cookie,5,1.0,5.0,Digital Wallet,Takeaway,2023-07-13
9039,TXN_4843989,Tea,4,1.5,6.0,Digital Wallet,Takeaway,2023-09-30
4961,TXN_8379815,Smoothie,5,NaN,20.0,Credit Card,NaN,2023-07-31
7926,TXN_2152054,Cake,2,3.0,6.0,Digital Wallet,NaN,2023-05-11
5466,TXN_5090839,Sandwich,5,4.0,20.0,Cash,NaN,2023-03-06

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  str
 1   Item              9667 non-null   str
 2   Quantity          9862 non-null   str
 3   Price Per Unit    9821 non-null   str
 4   Total Spent       9827 non-null   str
 5   Payment Method    7421 non-null   str
 6   Location          6735 non-null   str
 7   Transaction Date  9841 non-null   str
dtypes: str(8)
memory usage: 625.1 KB

In [6]:
# Number of missing values per column
df.isnull().sum()

Transaction ID         0
Item                 333
Quantity             138
Price Per Unit       179
Total Spent          173
Payment Method      2579
Location            3265
Transaction Date     159
dtype: int64

In [7]:
# Missing value percentage per column
df.isnull().sum() / len(df) * 100

Transaction ID       0.00
Item                 3.33
Quantity             1.38
Price Per Unit       1.79
Total Spent          1.73
Payment Method      25.79
Location            32.65
Transaction Date     1.59
dtype: float64

In [8]:
# Total missing values
df.isnull().sum().sum()

np.int64(6826)

In [9]:
# Total missing values in percentage
df.isnull().sum().sum() / (len(df)*len(df.columns)) * 100

np.float64(8.5325)

In [10]:
error_df = df[['Item','Payment Method', 'Location']]
error_df.head(3)

     Item Payment Method  Location
0  Coffee    Credit Card  Takeaway
1    Cake           Cash  In-store
2  Cookie    Credit Card  In-store

In [11]:
for col in error_df.columns:
    print(f"Unique Values in {col} column: \n{error_df[col].unique()}\n")
error_df = error_df.drop(columns=['Item'], axis='columns')  # Item column being dropped since its solution is found i.e 
                                                            # by dropping the rows with missing values

Unique Values in Item column:
<StringArray>
[  'Coffee',     'Cake',   'Cookie',    'Salad', 'Smoothie',  'UNKNOWN',
 'Sandwich',        nan,    'ERROR',    'Juice',      'Tea']
Length: 11, dtype: str

Unique Values in Payment Method column:
<StringArray>
['Credit Card', 'Cash', 'UNKNOWN', 'Digital Wallet', 'ERROR', nan]
Length: 6, dtype: str

Unique Values in Location column:
<StringArray>
['Takeaway', 'In-store', 'UNKNOWN', nan, 'ERROR']
Length: 5, dtype: str

In [12]:
error_set = ['UNKNOWN', 'ERROR', None]

In [13]:

for cols in error_df.columns:
    print(f"Column {error_df[cols].value_counts()}\n")
    print(f"\nNull values count: {error_df[cols].isnull().sum()}\n")

Column Payment Method
Digital Wallet    2291
Credit Card       2273
Cash              2258
ERROR              306
UNKNOWN            293
Name: count, dtype: int64


Null values count: 2579

Column Location
Takeaway    3022
In-store    3017
ERROR        358
UNKNOWN      338
Name: count, dtype: int64


Null values count: 3265

## Findings 
* There are 10k rows and 8 columns of data
* About 8% of the data is missing, which is not a lot and can be fixed by dropping or imputing the missing values.
* "Payment Method" and "Location" columns have the most missing data, and this is needed to be handled carefully.
* All data types of are in str data type, which needs to be converted to appropriate data types for analysis. 
* Column names should be in snake_format for easy access and readability.
* Missing values are not only in NaN format but some are in texts like "ERROR", "UNKNOWN" etc., which need to be handled separately and very carefully.
* If we count the number of wrong vales, like "UNKNOWN" or "ERROR" in Payment and Location columns, and add it with number of null rows, the number of actual missing data adds up more than just the null data, thereby there needs to be handled carefully or can be dropped in case of confusion since the percentage is comparatively low enough from the total data. 
* A somewhat promision soltution that can be applies to the above problem would be imputing the wrong values and missing values with mode.
* For the missing values of the Item column, we chould drop the rows with respect to null values of that column since we dont know the menu to find out the missing items, and the null data percentage is very low enough to take this decision I guess.